# Generated by Django 5.1.1 on 2024-11-11 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_name", models.CharField(max_length=30)),
                (
                    "bus_type",
                    models.CharField(
                        choices=[("ac", "AC"), ("non-ac", "NON-AC")], max_length=10
                    ),
                ),
                ("bus_capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sourse", models.CharField(max_length=20)),
                ("destinations", models.CharField(max_length=20)),
                (
                    "bus_rout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_managment.bus",
                    ),
                ),
            ],
        ),
    ]
