# Generated by Django 5.1.1 on 2024-11-13 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_time", models.TimeField()),
                ("arrivale_time", models.TimeField()),
                ("tickit_price", models.IntegerField()),
                ("avalable_seates", models.IntegerField()),
                (
                    "bus_route_schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_managment.busroute",
                    ),
                ),
            ],
        ),
    ]
