# Generated by Django 5.1.1 on 2024-11-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0002_busschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="busschedule",
            name="bus_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
