# Generated by Django 5.1.1 on 2024-11-13 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0004_alter_busschedule_bus_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busschedule",
            name="bus_route_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bus_managment.busroute"
            ),
        ),
    ]
