# Generated by Django 5.1.1 on 2024-11-13 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0005_alter_busschedule_bus_route_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busschedule",
            name="bus_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bus_managment.bus",
            ),
        ),
    ]
