# Generated by Django 5.1.1 on 2024-11-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0007_alter_busschedule_bus_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="busschedule",
            old_name="bus_name",
            new_name="bus",
        ),
    ]
