# Generated by Django 5.1.1 on 2024-11-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0009_intermidiatestop"),
    ]

    operations = [
        migrations.AddField(
            model_name="intermidiatestop",
            name="intermidiate_stop_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
