# Generated by Django 5.1.1 on 2024-11-21 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0011_busbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="busbooking",
            name="bus_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bus_managment.busschedule",
            ),
        ),
        migrations.AddField(
            model_name="busbooking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("panding", "Panding"),
                    ("success", "Success"),
                    ("cancle", "Cancle"),
                ],
                default="panding",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="busbooking",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=10
            ),
        ),
    ]
