# Generated by Django 5.1.1 on 2024-11-22 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bus_managment",
            "0012_busbooking_bus_schedule_busbooking_payment_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="busbooking",
            name="booking_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_ammount", models.IntegerField()),
                ("payment_method", models.CharField(max_length=20)),
                ("payment_date", models.DateTimeField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("panding", "Panding"),
                            ("success", "Success"),
                            ("cancle", "Cancle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cancellation_reason", models.TextField()),
                (
                    "bus_booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_managment.busbooking",
                    ),
                ),
            ],
        ),
    ]
