# Generated by Django 5.1.1 on 2024-11-25 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0013_busbooking_booking_date_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="bus_booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bus_managment.busbooking",
            ),
        ),
    ]
