# Generated by Django 5.1.1 on 2024-11-25 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0014_alter_payment_bus_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="bus_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bus_managment.busbooking",
            ),
        ),
    ]
