# Generated by Django 5.1.1 on 2024-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0015_alter_payment_bus_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_date",
            new_name="cancellation_date",
        ),
        migrations.AlterField(
            model_name="busbooking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("panding", "Panding"),
                    ("success", "Success"),
                    ("cancle", "Cancle"),
                    ("refund", "Refund"),
                ],
                default="panding",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("panding", "Panding"),
                    ("success", "Success"),
                    ("cancle", "Cancle"),
                    ("refund", "Refund"),
                ],
                max_length=20,
            ),
        ),
    ]
