# Generated by Django 5.1.1 on 2024-11-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bus_managment",
            "0017_alter_busbooking_bus_schedule_alter_busbooking_user_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="sefty",
            new_name="safety",
        ),
        migrations.RenameField(
            model_name="feedback",
            old_name="staf_behavioue",
            new_name="staff_behaviour",
        ),
    ]
