# Generated by Django 5.1.1 on 2024-11-27 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0018_rename_sefty_feedback_safety_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="bus_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus_schedule",
                to="bus_managment.busschedule",
            ),
        ),
        migrations.AlterField(
            model_name="busbooking",
            name="bus_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="bus_managment.busschedule",
            ),
        ),
        migrations.AlterField(
            model_name="busroute",
            name="bus_rout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus",
                to="bus_managment.bus",
            ),
        ),
        migrations.AlterField(
            model_name="busschedule",
            name="bus_route_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus_route",
                to="bus_managment.busroute",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to="bus_managment.busbooking",
            ),
        ),
    ]
