# Generated by Django 5.1.1 on 2024-11-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bus_managment",
            "0019_feedback_bus_schedule_alter_busbooking_bus_schedule_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="busbooking",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
