# Generated by Django 5.1.1 on 2024-11-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0020_busbooking_payment_intent_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="busbooking",
            name="selected_seats",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
