# Generated by Django 5.1.1 on 2024-11-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0021_busbooking_selected_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busbooking",
            name="seats",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
