# Generated by Django 5.1.1 on 2024-12-02 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_managment", "0022_alter_busbooking_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to="bus_managment.busbooking",
            ),
        ),
    ]
